# Generated by Django 6.0.6 on 2026-06-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('temporadas', models.IntegerField()),
                ('status', models.CharField(choices=[('ASSISTINDO', 'Assistindo'), ('FINALIZADA', 'Finalizada'), ('ABANDONADA', 'Abandonada')], max_length=20)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
